# Generated by Django 5.2.4 on 2025-08-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_auto_reply_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailinquiry',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_auto_reply_project.inquiryuser'),
        ),
        migrations.AlterField(
            model_name='inquiryquestion',
            name='answer',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryquestion',
            name='email_inquiry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_auto_reply_project.emailinquiry'),
        ),
    ]
